### PR TITLE
furynick gen tx

### PR DESCRIPTION
**Pull request by falanfistik**

### CODE REVIEW

**Review by falanfistik — COMMENTED** [review]
peers

**Review by falanfistik — COMMENTED** [review]
port changed

**Review by falanfistik — COMMENTED** [review]
gentx and peers updated

**Review by albertandrejev — DISMISSED** [review]

**Review by falanfistik — COMMENTED** [review]
Moniker: furynick
Website: https://thenop.io/
Team: furynick#2535 mahof#6504 Emre NOP#7479 ! SECARD !#7408
Neutronvaloper address: neutronvaloper1jtfxpmysfs42zr3qs562y7tj3acw9490mckk64

**Review by albertandrejev — APPROVED** [review]

**Pull request merged**
