### PR TITLE
Golden Ratio Staking Updated GenTx

### PR DESCRIPTION
**Pull request by Golden-Ratio-Staking**
- Moniker: Golden Ratio Staking
- Website: https://www.goldenstaking.com
- Twitter: https://www.twitter.com/GoldenStaking
- Discord: GoldenRatioStaking#0833

- Valoper: neutronvaloper1m0jthg0760vpstngmz5l7a6duwx4am3eqhexj3

### CODE REVIEW

**Review by albertandrejev — APPROVED** [review]

**Comment by Medniyy** [comment]
Hey there! Some additional details should be provided in the description! 
Check this:

https://github.com/neutron-org/testnets/tree/main/quark#fill-pull-request-description

**Comment by Golden-Ratio-Staking** [comment]
@Medniyy Updated in comment above! Do that work?

**Comment by Medniyy** [comment]
Yep! Thanks for it! You're so fast 😎

**Comment by Golden-Ratio-Staking** [comment]
Thank you! <3

**Pull request merged**
