### PR TITLE
nodepro.xyz-gentx Upload.json

### PR DESCRIPTION
**Pull request by gokmenkutuk**

### CODE REVIEW

**Review by albertandrejev — APPROVED** [review]

**Comment by gokmenkutuk** [comment]
nodepro.xyz
https://nodepro.xyz
gloreix#1617
neutronvaloper10j3nq2l0axq6hccl5gj2wwp7zlcmv4t5grk5rr

**Comment by gokmenkutuk** [comment]
Hi @albertandrejev is there something missing about my submission?

**Review by albertandrejev — APPROVED** [review]

**Comment by albertandrejev** [comment]
No, everything if fine.

**Comment by gokmenkutuk** [comment]
Thank you @albertandrejev

**Pull request merged**
